In [30]:
import pandas as pd
import numpy as np

In [31]:
#Question 1
x = np.array([0,1,2,3,4,5,6,7,8])
x.resize([3,3])

In [32]:
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [33]:
#Question 2
x = np.array([0,1,2,3,4,5,6,7,8,9])
x[1::2] =-1
print(x)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [34]:
#Question 3
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89]) 
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])
print(np.where(x>y))
print(np.where(x==y))

(array([1, 2, 4, 5, 6, 7, 8, 9]),)
(array([0]),)


In [35]:
#Question 4
x= np.arange(100).reshape(5,-1)
print(x[:,:4,])

[[ 0  1  2  3]
 [20 21 22 23]
 [40 41 42 43]
 [60 61 62 63]
 [80 81 82 83]]
