In [1]:
import torch

## 1

In [54]:
a = torch.tensor(1.0, requires_grad = True)
b = torch.tensor(4.0, requires_grad = True)

x = 2*a + 3*b
y = 5*a**2 + 3*b**3
z = 2*x + 3*y

z.backward()

print(a.grad)

# Analytical
dzx = 2
dxa = 2
dzy = 3
dya = 10*a
dza = dzx*dxa + dzy*dya
print(dza)

tensor(34.)
tensor(34., grad_fn=<AddBackward0>)


## 2

In [96]:
x = torch.tensor([-4.0], requires_grad = True)
w = torch.tensor([2.0], requires_grad = True)
b = torch.tensor([-8.0], requires_grad = True)


u = w*x

v = u+b


a = v if v>0 else v*0

a.backward()

print(w.grad)

# Analytical
dav = 1 if a>0 else 0.0
dvu = 1
duw = x
dw = dav*dvu*duw
print(dw)

tensor([-0.])
tensor([-0.], grad_fn=<MulBackward0>)


## 3

In [181]:
x = torch.tensor([4.0], requires_grad = True)
w = torch.tensor([7.0], requires_grad = True)
b = torch.tensor([2.0], requires_grad = True)


u = w*x

v = u+b

t1 = -v
t2 = torch.exp(t1)
t3 = 1+t2
a = 1.0/t3


a.backward()

print(w.grad)

# Analytical
da3 = -1.0/(t3**2)
da2 = da3*1
da1 = da2*torch.exp(t1)
da = da1*-1


print(da*x)

tensor([3.7430e-13])
tensor([3.7430e-13], grad_fn=<MulBackward0>)



### 4

In [180]:
x = torch.tensor([2.0], requires_grad = True)


a = -x**2
b = -2*x
c = -torch.sin(x)
d = a+b+c
e = torch.exp(d)

e.backward()

print(x.grad)

dax = -2*x
dbx = -2
dcx = -torch.cos(x)
ddx = dax+dbx+dcx
dex = e*ddx
print(dex)

tensor([-0.0008])
tensor([-0.0008], grad_fn=<MulBackward0>)


## 5


In [182]:
x = torch.tensor([2.0], requires_grad = True)
a = 6*x
b = 7*x**2
c = 3*x**3
d = 8*x**4
y = a+b+c+d+3

y.backward()

print(x.grad)

#Analytical
da = 6
db = 7*2*x
dc = 3*3*x**2
dd = 8*4*x**3
dy = da+db+dc+dd

print(dy)

tensor([326.])
tensor([326.], grad_fn=<AddBackward0>)


## 6

In [193]:
x = torch.tensor([2.0], requires_grad=True)
y = torch.tensor([1.0], requires_grad = True)
z = torch.tensor([3.0], requires_grad = True)

a = 2*x
b = torch.sin(y)
c = (a/b)
d = z*c
e = torch.log(1+d)
f = torch.tanh(e)
a.retain_grad()
b.retain_grad()
c.retain_grad()
d.retain_grad()
e.retain_grad()
f.retain_grad()

f.backward()

print(y.grad)

# Analytical
dfe = 1-(torch.tanh(e)**2)
ded = 1.0/(d+1)
ddc = z
dcb = -a/(b**2)
dby = torch.cos(y)
print(dfe*ded*ddc*dcb*dby)

print(x.grad)

for i in (f,e,d,c,b,a):
    print(i.grad.item())

tensor([-0.0102])
tensor([-0.0102], grad_fn=<MulBackward0>)
tensor([0.0080])
1.0
0.01702888309955597
0.0011158620472997427
0.003347586141899228
-0.018910957500338554
0.003978255204856396
